### ISSUE TITLE
Release project

### ISSUE THREAD

**Issue by fmsbeekmans** [Tenchi2xh/Scurses#5]
Could you release the project so that it can be used as a dependency in other projects? For example on Bintray.

**Comment by Tenchi2xh** [comment]
Sure, I will see about that during the weekend. I'll merge #2, freshen up a bit more and try and do a release

**Comment by gchudnov** [comment]
it would be great if @Tenchi2xh merged #2 and released it. :+1:

**Comment by Tenchi2xh** [comment]
Sorry for the long wait, I finally released the two projects on Maven, the dependencies are now in the readme!
(Sonatype didn't make this easy)
